In [1]:
import tensorflow as tf

## I. Tensor and Variable

In [2]:
tensor_zero_d = tf.constant(4)
tensor_zero_d

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [3]:
tensor_one_d = tf.constant([1, 2, 3, 4])
tensor_one_d

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([1, 2, 3, 4])>

In [5]:
tensor_two_d = tf.constant([[1, 2], [3, 4]])
tensor_two_d

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [10]:
tensor_three_d = tf.constant(
    [
        [[1, 2, 4.0], [3, 4, 2]],
        [[5, 6, 0], [7, 8, 1]]
    ]
)
tensor_three_d.ndim

3

In [8]:
tensor_three_d.shape

TensorShape([2, 2, 3])

Có thể dùng hàm tf.cast để chuyển đổi kiểu dữ liệu của tensor

In [13]:
print(tensor_three_d) # dtype = float32
tensor_three_d = tf.cast(tensor_three_d, tf.int16) # dtype = int16
print(tensor_three_d)

tf.Tensor(
[[[1. 2. 4.]
  [3. 4. 2.]]

 [[5. 6. 0.]
  [7. 8. 1.]]], shape=(2, 2, 3), dtype=float64)
tf.Tensor(
[[[1 2 4]
  [3 4 2]]

 [[5 6 0]
  [7 8 1]]], shape=(2, 2, 3), dtype=int16)


In [16]:
import numpy as np

# convert numpy array to tensor
np_array = np.array([1, 2, 4])
print(np_array)
converted_tensor = tf.convert_to_tensor(np_array)
print(converted_tensor)

[1 2 4]
tf.Tensor([1 2 4], shape=(3,), dtype=int32)


In [17]:
# eye method
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=None, # None -> num_columns = num_rows
    batch_shape=None, # None -> batch -> number of dim
    dtype=tf.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [20]:
eye_tensor = tf.eye(
    num_rows=3,
    num_columns=5, 
    batch_shape=[2,], 
    dtype=tf.float32,
    name=None
)
print(eye_tensor)

tf.Tensor(
[[[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]

 [[1. 0. 0. 0. 0.]
  [0. 1. 0. 0. 0.]
  [0. 0. 1. 0. 0.]]], shape=(2, 3, 5), dtype=float32)


In [26]:
# fill method
fill_tensor = tf.fill(
    dims = [2, 3], value = 9, name = None
)
print(fill_tensor)

tf.Tensor(
[[9 9 9]
 [9 9 9]], shape=(2, 3), dtype=int32)


In [27]:
# shape method: return the tensor containing the shape of input tensor
tf.shape(
    input = fill_tensor
)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([2, 3])>

In [28]:
# rank method: return tensor's rank
tf.rank(
    input = fill_tensor
)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
# random method
random_tensor = tf.random.normal(
    shape = [3, 2], mean = 0.0, stddev = 1.0, dtype = tf.float32, seed = None, name = None
)